name: build

on: 
  release:
    types: [released]

env:
    DOTNET_NOLOGO: true
    Configuration: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: build
        working-directory: ./src
        run: dotnet build

      - name: test
        working-directory: ./src
        run: dotnet test

      - name: pack
        working-directory: ./src
        run: dotnet pack -p:version=${GITHUB_REF#refs/*/v} -o "$PWD/nuget"

      - name: nuget
        working-directory: ./src
        run: dotnet nuget push "$PWD/nuget/**/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate